# Generated by Django 2.2.6 on 2019-10-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('precio', models.TextField(max_length=1000)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
